### ISSUE TITLE
DataVec Inference pipeline

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/DataVec#116]
Idea: Take a uri -> and output an ndarray.

Right now I am looking at setting up an abstraction on top of datavec-camel to handle the ability to define pipelines based on just an input uri. From that we should be able to build better abstractions for running inference pipelines using datavec. This should also improve the flexibility of embedding things liek a transform process. 

Note that for this to work we will need a datavec local executor.

**Comment by huitseeker** [comment]
Blocked by #87

**Comment by huitseeker** [comment]
See also #78

**Comment by AlexDBlack** [comment]
Already planned as part of rewrite
