### ISSUE TITLE
DataVec PairWiseTransforms

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/DataVec#117]
Right now we don't really have pairwise transforms (apply a transform such as addition/subtraction) with another column as input. We need to add a BasePairWiseTransform class yet.

**Comment by AlexDBlack** [comment]
We have pairwise transforms - addition/subtraction/etc (everything in https://github.com/deeplearning4j/DataVec/blob/master/datavec-api/src/main/java/org/datavec/api/transform/MathOp.java)
So I'll close this. If there's anything else we need beyond that, we can open a new issue.

For example https://github.com/deeplearning4j/DataVec/blob/master/datavec-api/src/main/java/org/datavec/api/transform/transform/doubletransform/DoubleColumnsMathOpTransform.java#L31-L40
https://github.com/deeplearning4j/DataVec/blob/master/datavec-api/src/main/java/org/datavec/api/transform/transform/BaseColumnsMathOpTransform.java
