### ISSUE TITLE
Add unified interface and testing framework for transform process executor

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/DataVec#124]
With the new datavec local feature being worked on it would be a good idea to add a unified testing framework with spark or local as various "backends" ala nd4j. We also need a unified interface for the executors to run transform process at the api level.

1 initial step will be to port what existing tests we have to a new interface after we get the initial transform executor interface in the api figured out.

**Comment by raver119** [comment]
Is this issue still viable?

**Comment by agibsonccc** [comment]
I'd say yes, it would be great to have this at some point.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/issues/5183
