### ISSUE TITLE
Add functionality to convert INDArray to image

### ISSUE THREAD

**Issue by iw876** [deeplearning4j/DataVec#133]
Use cases:
- export the result of: image -> RBM -> image
- ability to export images during the learning phase as a alternative for ShowImageTransform
    -> more flexible
    -> no X11 needed

**Comment by raver119** [comment]
"image" word has quite vague definition. There's 100500 different input formats even for 2D images, and then there's special 3D image formats out there, like MRI. 

Do you want something simple, like ShowImageTransform, but without X server needed, or you have something special in mind?

**Comment by agibsonccc** [comment]
I'm closing this. This is more related maybe to the UI?
