### ISSUE TITLE
NumberFormatException with the column declared as Long or Double

### ISSUE THREAD

**Issue by nextremerFCL** [deeplearning4j/DataVec#135]
In my class, I create a Schema with the column as Long (same problem with Double)

During the execution I have the following error :
```
Exception in thread "main" java.lang.NumberFormatException: For input string: "85789544141562"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:583)
    at java.lang.Integer.parseInt(Integer.java:615)
    at org.datavec.api.writable.Text.toInt(Text.java:611)
    ...
```
I have not tested all number's types.

**Comment by saudet** [comment]
We'll need a way to reproduce that. Testing with existing examples and large numbers reveals no issues.

**Comment by agibsonccc** [comment]
NumberFormatException might come from overflow? @saudet did you test with this number specifically?

**Comment by saudet** [comment]
Yes I did, just gets filtered out

**Comment by saudet** [comment]
The problem occurs on this line:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/datasets/datavec/RecordReaderDataSetIterator.java#L253
Basically it seems like labels have to be 32-bit integers. Is this documented somewhere?
