### ISSUE TITLE
Optimize Spark TransformProcess execution

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/DataVec#14]
Currently, (almost) each step of a TransformProcess (when executed on Spark) is a `JavaRDD<List<Writable>>` to `JavaRDD<List<Writable>>` operation. However, we can actually chain multiple operations together, such that each RDD->RDD acutally implements multiple operations.
In theory, this should reduce the amount of overhead for Spark, resulting in faster execution.

Additionally, for join operations, repartitioning by the key should reduce the amount of network shuffling that is required.

**Comment by huitseeker** [comment]
Operations that are a succession of `map` or `flatMap` calls (along with all other operations that do not require a shuffle) are executed in a single task already (see § Execution DAG in [url](https://databricks.com/blog/2015/06/22/understanding-your-spark-application-through-visualization.html) for details).

So what it takes to understand how "chaining" operations could improve performance is to tally the operations that we introduce in a `TransformProcess` that "break" this native chaining. Such as : 
- shuffle operations (e.g. reduce)
- serialization to disk

Are there pointers to specific such places you can think of, @AlexDBlack  ?

**Comment by AlexDBlack** [comment]
Yes, I'm aware that Spark will apply multiple tasks for each partition.
Not sure exactly what I had in mind when I opened this - but I suspect I was thinking of pushing this down to the level of DataVec.

I'll close this in favor of my recent basecamp issue/proposal that supercedes this.
