### ISSUE TITLE
Show Image Transform unwanted padding in the window

### ISSUE THREAD

**Issue by ZhongBaby** [deeplearning4j/DataVec#149]
I'm sure my image input is 100x100 which looks like this:
![14](https://cloud.githubusercontent.com/assets/8222739/21469708/2f16d7ba-ca9d-11e6-80e4-5f3833f71053.jpg)
But when I use show image transform to show it.
I got some unwanted padding in the right of the window.
![2](https://cloud.githubusercontent.com/assets/8222739/21469709/32aca29c-ca9d-11e6-8913-9e44f2f16a21.PNG)

**Comment by saudet** [comment]
This doesn't happen here with the ImagePipelineExample. Could you provide a few lines of code to reproduce this? Thanks!

**Comment by ZhongBaby** [comment]
alright, maybe it's my machine problem
