### ISSUE TITLE
Warp Image transform may be filled the black background with edge color

### ISSUE THREAD

**Issue by ZhongBaby** [deeplearning4j/DataVec#150]
For example if I want to train a neural net to classify character in image.
I think after the warp image transformation, the black background maybe filled with edge color so that it is closer to unseen dataset distribution.
I think the second image is better.
![1](https://cloud.githubusercontent.com/assets/8222739/21469717/ab482f32-ca9d-11e6-9c4d-abafcf3327f4.PNG)
![1 - copy](https://cloud.githubusercontent.com/assets/8222739/21469718/abc0778a-ca9d-11e6-8ec4-a89947796028.PNG)

**Comment by saudet** [comment]
Done! We can now do `new WarpImageTransform(...).borderMode(BORDER_REPLICATE)` to get that.
