### ISSUE TITLE
Color Conversion Transform Assertion Failed with Image Channels=1

### ISSUE THREAD

**Issue by ZhongBaby** [deeplearning4j/DataVec#151]
I use Color Conversion, when I combine it with Show Image Transform into a MultiImageTransform.
It's ok.

But when I use only Color Conversion, In the Stack Trace I found that the image loaded by NativeImageLoader is ONLY ONE CHANNEL!

My training image has 3 channels and this only happend when I don't use ShowImageTransform.

**Comment by saudet** [comment]
You're going to need to start providing code. It's hard to guess what you're doing wrong.
