### ISSUE TITLE
WavFileRecordReader - iter is null on first call of hasnext() -> exception

### ISSUE THREAD

**Issue by FloThinksPi** [deeplearning4j/DataVec#153]
Watch that Gist for example Code of issue.
https://gist.github.com/FloThinksPi/186f26087a0caf60579cd1eeb9989504

On 1. Call of Record Readers hasnext() function, the Record readers iter is null.
![image](https://cloud.githubusercontent.com/assets/5863788/21543787/ca81e7b0-cdc9-11e6-856e-be8f6733f7ee.png)

which causes the exception in the gist above.
@agibsonccc said he knows whats going on , i dont :smiley: https://gitter.im/deeplearning4j/deeplearning4j?at=5864fe92058ca96737a3a75d

Best Regards 
Flo

**Comment by saudet** [comment]
FYI, FFmpeg supports a lot of file formats, so once we get FFmpeg in there that will work for wav files as well.

**Comment by FloThinksPi** [comment]
@saudet will ffmpeg will by a option anyway ? since you talked about license problems in issue #104

**Comment by saudet** [comment]
@FloThinksPi Yes sure, the plan is to use FFmpeg for that. We resolved the licensing issue by leaving it up to users to uncomment the dependency on FFmpeg.

**Comment by saudet** [comment]
I've fixed the issue as per the commit above, and your code now works, after removing the extra dot in `allowedExtensions`:
```java
protected static final String[] allowedExtensions = {"wav"};
```
