### ISSUE TITLE
StringToDouble function needed

### ISSUE THREAD

**Issue by keskella** [deeplearning4j/DataVec#193]
There needs to be a way to clean up data that is like this: 
amount,date,globalTradeID,rate,total,tradeID,type
"""7288.99801187""","""2016-05-07 20:17:15""",29852250,"""0.00010200""","""0.74347779""",97681,"""sell"""
"""215.64399137""","""2016-05-07 20:17:15""",29852249,"""0.00010202""","""0.02199999""",97680,"""sell"""

as you can see all the doubles are within quotes, so stringtomap transform only can do the quote removal, but not a transition to double.

**Comment by saudet** [comment]
That has been added at the CSVRecordReader level: https://github.com/deeplearning4j/DataVec/blob/master/datavec-api/src/main/java/org/datavec/api/records/reader/impl/csv/CSVRecordReader.java#L77  In your case, specify `"\"\"\""` as argument for "quote".
