### ISSUE TITLE
JavaDoc fixes

### ISSUE THREAD

**Issue by tomthetrainer** [deeplearning4j/DataVec#194]
Video Record Reader JavaDoc is sparse and has typos

https://deeplearning4j.org/datavecdoc/org/datavec/image/recordreader/VideoRecordReader.html

"A video is just a moving window of pictures. It should be processed as cuh. This iterates over a root folder and returns a"

Probably malformed comment, easy fix

**Comment by abossenbroek** [comment]
@tomthetrainer  happy to help but first need to fix some issues with datavec on my side. Let me know what would be a good start.

**Comment by tomthetrainer** [comment]
For this ticket, it looks like the first javadoc comment is just incomplete and needs to be completed. 

A number of methods in ND4J need documented regarding wether they create a copy or work in place. 
#909

https://github.com/deeplearning4j/deeplearning4j/issues/909

I could create a list of issues with javadoc as the problem, and we can find time or you can help patch them.

**Comment by kepricon** [comment]
fill the hole :)
https://github.com/deeplearning4j/DataVec/commit/cabe6fa3d4a15a94f04c03027176306e884dffba
