### ISSUE TITLE
LibSvmRecordReader parsing

### ISSUE THREAD

**Issue by mbofb** [deeplearning4j/DataVec#207]
There are exceptions while reading a libsvm file with LibSvmRecordReader. If the first row does not contain an entry for the highest dimension of the dataset, it causes the exception https://gist.github.com/mbofb/000e47d4488b92092add3b152037e213

If this fact is circumvented (by having the highest dimension in the first row), it processes without any logging until a "java.lang.OutOfMemoryError: Java heap space" (https://gist.github.com/mbofb/ca65f3d9761c9457596e264f96253d47) occurs (after appr. 9GB memory consumed)
The hereby used dimensions are rather tiny (e.g. 100 instances with max dimension 693 (https://github.com/apache/spark/blob/master/data/mllib/sample_libsvm_data.txt)) and should easly fit into memory as dense vectors. Even for only a subset of 11 instances the behaviour (processing to OutOfMemoryError) was the same.

**Comment by saudet** [comment]
I am not able to reproduce this issue with the following code. It seems to parse everything just fine.
```java
        RecordReader rr = new LibSvmRecordReader();
        Configuration conf = new Configuration();
        conf.set(LineRecordReader.APPEND_LABEL, "true");
        rr.initialize(conf, new FileSplit(new File("/tmp/sample_libsvm_data.txt")));

        int count = 0;
        while (rr.hasNext()) {
            count++;
            System.out.println(rr.next());
        }
        System.out.println(count);
```
Could you also provide some sample code that fails? Thank you

**Comment by mbofb** [comment]
final LibSvmRecordReader recordReader = new LibSvmRecordReader();
        final Configuration configuration = new Configuration();
        configuration.set(LineRecordReader.APPEND_LABEL, "true");
        recordReader.initialize(configuration, new FileSplit(new File(this.inputFile)));
        final RecordReaderDataSetIterator recordReaderDataSetIterator = new RecordReaderDataSetIterator(recordReader, batchSize, 0, 2);
        logger.info("columns: " + recordReaderDataSetIterator.inputColumns());

java.lang.IllegalStateException: Mis matched lengths: [658] != [684]
	at org.nd4j.linalg.util.LinAlgExceptions.assertSameLength(LinAlgExceptions.java:40)
	at org.nd4j.linalg.api.ops.BaseTransformOp.<init>(BaseTransformOp.java:47)
	at org.nd4j.linalg.api.ops.impl.transforms.Set.<init>(Set.java:24)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.assign(BaseNDArray.java:1223)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.put(BaseNDArray.java:1973)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.putRow(BaseNDArray.java:3500)
	at org.nd4j.linalg.dataset.DataSet.merge2d(DataSet.java:270)
	at org.nd4j.linalg.dataset.DataSet.merge(DataSet.java:183)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:195)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:389)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.inputColumns(RecordReaderDataSetIterator.java:323)

**Comment by turambar** [comment]
@mbofb You need to set the `NUM_FEATURES` property in your configuration, as shown in this gist: https://gist.github.com/anonymous/85224d25e12a191ce5c5320e3c1e1388

Likewise, when using the SvmLightRecordReader, you need to set the `NUM_ATTRIBUTES` property.

**Comment by turambar** [comment]
@saudet Probably what we need here is a warning and/or informative error message when these properties aren't set. I'll see about sending a PR. There's another potential bug -- if the features use zero-based indexing, the reader will go into an infinite loop.

**Comment by turambar** [comment]
@mbofb I could not reproduce the memory issue. I was able to load the sample data just fine.

**Comment by saudet** [comment]
So it has something to do with RecordReaderDataSetIterator?

**Comment by saudet** [comment]
This issue appears to be fixed, but let us know if this isn't the case. Thanks!
