### ISSUE TITLE
Remove all imports from Loggers

### ISSUE THREAD

**Issue by aydin1918** [deeplearning4j/DataVec#214]
Hello, guys. 

Please remove all loggers from JAR'files

For example - **slf4j**

Due to exceptions like - ClassNotFound or StaticLoggerBinder.

It is ok, when you use logger while developing or testing, but remove imports to them before exporting to JAR file

Thanks in Advance

**Comment by raver119** [comment]
Show your pom.xml please :)

**Comment by aydin1918** [comment]
@raver119  I did not use pom.xml

I downloaded JAR (version: 0.8.0) files directly from maven repository

**Comment by raver119** [comment]
Ah. That explains. No way then, sorry. All this stuff is suited for use of build management systems, like maven or sbt or whatever.
