### ISSUE TITLE
CompactHeapStringList - not found in the latest JAR file

### ISSUE THREAD

**Issue by aydin1918** [deeplearning4j/DataVec#215]
Hello, guys

There is no class in latest JAR file from maven -  **CompactHeapStringList** which uses FileSplit class. 

And you can catch exception - NoClassDefFoundError

**Comment by raver119** [comment]
Show your pom.xml please

**Comment by aydin1918** [comment]
But you can solve this by creating you own package - org.nd4j.linalg.collection and copy all source code from GitHub

**Comment by raver119** [comment]
You're probably just using outdated version. Just show your pom.xml please :)

**Comment by raver119** [comment]
All this stuff is suited for use of build management systems, like maven or sbt or whatever.
Please consider using maven or any other build system.
