### ISSUE TITLE
Transforms should be chainable and, optionally, randomly invoked

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/DataVec#217]
For the purpose of image classification and learning, transforms like CropImageTransform and WarpImageTransform need to be chainable and have the option of being randomly invoked throughout the chain. This would allow for a more homogenous training set and contribute to a smoother learning curve.

**Comment by raver119** [comment]
We have concept in few nlp places, where we allow combination of abstractions.
Maybe that's what we need here? Some transform holder, that's built from any number of real transforms, and applies them sequentially or with shuffle?

**Comment by crockpotveggies** [comment]
I like the transform holder idea a lot. Shuffle should probably be optional, since some image pipelines may distort an image in a negative way?

**Comment by crockpotveggies** [comment]
@raver119 can you link me to where this is done in NLP?

**Comment by raver119** [comment]
It's just abstraction/pattern, not sure how particular impl is going to help you :)

This: 
https://github.com/deeplearning4j/deeplearning4j/blob/1f8af820c29cc5567a2c5eaa290f094c4d1492a7/deeplearning4j-nn/src/main/java/org/deeplearning4j/datasets/iterator/CombinedPreProcessor.java#L15-L15

Or this: 
https://github.com/deeplearning4j/deeplearning4j/blob/1f8af820c29cc5567a2c5eaa290f094c4d1492a7/deeplearning4j-nlp-parent/deeplearning4j-nlp/src/main/java/org/deeplearning4j/text/sentenceiterator/AggregatingSentenceIterator.java

Idea is the same behind those implementation.
We have class implementing some interface, that holds some other implementations of the same interface, and ivoke them sequentially. If you want to invoke them in random order - it's fairly easy to add  as well.

**Comment by crockpotveggies** [comment]
Pattern helps me to understand what has been done already and trying to stay within our established practices.

I'm thinking we create a `CombinedImageTransform` which can take multiple `ImageTransform` classes. It takes a `List<InvocationEnum, ImageTransform>` which allows the user to define the pipeline and whether that specific element in the pipeline is sequentially or randomly evoked.

Ideas?

**Comment by raver119** [comment]
I'd keep it as List. 

In this case you can pass transform 0 as mandatory for all paths, and transofrm 1 as another combined transform, which will invoke its members in random order

**Comment by crockpotveggies** [comment]
I don't think that'd work though if you, say, always need a random crop but don't always want to randomly warp an image. For example take the following pipeline:

1. (Always) RandomCrop
2. (Randomly) WarpImage
3. (Always) FlipImage

In some cases you might need the random crop to come first, otherwise if warp image was randomly invoked the image might be too distorted.

**Comment by raver119** [comment]
No, by random i mean random invocation order, not random invocation :)

**Comment by crockpotveggies** [comment]
Ah so you're happy with both my proposed input and you want to pass in an additional option for random ordering?

**Comment by raver119** [comment]
Yep, totally ok. However enum isn't really needed then. Just use double as probability, in 0.0 - 1.0 range, as invocation chance

**Comment by crockpotveggies** [comment]
+1 for double.
