### ISSUE TITLE
BufferedImage substitute for android on NativeImageLoader

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/DataVec#248]
#### Issue Description
http://stackoverflow.com/questions/43775338/deeplearning4j-class-file-for-java-awt-image-bufferedimage-not-found-on-androi/43776425#43776425
Please describe your issue, along with:
NativeImageLoader still uses BufferedImage, seems like a simple fix.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
* platform information (OS, etc)
* CUDA version, if used
* NVIDIA driver version, if in use

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by saudet** [comment]
Already fixed with pull #240.
