### ISSUE TITLE
Add a Dataset frontend to DataVec 

### ISSUE THREAD

**Issue by huitseeker** [deeplearning4j/DataVec#250]
Spark's DataSets (≠ DataFrames) past Spark 1.6.3, support binary data [if you provide an encoder for it](http://stackoverflow.com/a/39442829). For columnar data, which includes most of the customer data so far, this would allow a Dataset-based API to be faster to process (because of the query planning of Catalyst), off-heap (project Tungsten), and would allow early stopping (because of type inference in Datasets).

Deliverables
working prototype
Expected outcomes
much faster ETL, probing, errors at compile time. faster failure of ETL, direct tracking of transformations (in Spark UI)

**Comment by huitseeker** [comment]
SKIL issues are better placed in the SKIL repo

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/issues/5192
