### ISSUE TITLE
Add samplers as an ETL module 

### ISSUE THREAD

**Issue by huitseeker** [deeplearning4j/DataVec#251]
Class imbalance problems seem to be frequent for our use case, and weighted loss functions don't seem to be enough. They require methods for sampling data, bootstrapping, and duplicating data based on a label (ref). 

https://docs.google.com/document/u/1/d/19iCoT3kVtTxzOd72rvvMsMUiwq6sXhQVbjIwb9jkN-4/edit?usp=gmail#heading=h.fo3yjcilgbz5

**Comment by AlexDBlack** [comment]
Handling class imbalance better is something we definitely need. However, I'm not sure exactly what the best approach is here, even just for the sampling-based techniques.

For example,
- Do we produce a new dataset (say, a new CSV), with undersampling of frequent classes, or oversampling of infrequent classes?
- Do we build sampling into the RecordReader.next() method? (Easy enough for images, pretty hard to do for CSV etc)
- Do we preprocess our data and build this at the DL4J/ND4J level? https://github.com/deeplearning4j/nd4j/issues/1521#issuecomment-269857986

**Comment by AlexDBlack** [comment]
Will be handled in pending rewrite.
