### ISSUE TITLE
At transforms sequence offset operation

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/DataVec#257]
The idea: when dealing with sequence data, shift a number of columns by a specified number of steps

The most common use case here: predicting the values of a sequence N steps ahead.

**Comment by huitseeker** [comment]
Probably in the same batch as #239  (this is a call for a windowing API)

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/DataVec/blob/master/datavec-api/src/main/java/org/datavec/api/transform/transform/sequence/SequenceOffsetTransform.java

Was added here: https://github.com/deeplearning4j/DataVec/pull/285
