### ISSUE TITLE
Add a distinct (dedup) transform/filter

### ISSUE THREAD

**Issue by wmeddie** [deeplearning4j/DataVec#262]
#### Issue Description

It would be nice to have a distinct transform to de-duplicate data.

**Comment by huitseeker** [comment]
For the deduplicate, the dumb solution is just sorting and deduplicating successive elements, modulo eps on floating point fields. If that's not good enough, there's plenty of alternatives, but to choose the appropriate scope, more info would help:

-  when is this deduplication needed? initial analysis?
- can I just sort and remove successive equal records? if not, is it that you're compute bound?  
- if not,  it's probably a semantics question: what's the granularity you want for an MVP ? whole record good enough for now, modulo eps? (think of time series data, think of unique key fields)
- if so, how precise should it be ? can I be approximate (that helps) and leave a few duplicated lines? Should I remove exactly 100% of the dupes?

(bonus : what's occurring in your data that's creating these dupes ? do you know ? wrong join, erroneous duplication, distributed system, just dirty data ?)

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/issues/5195
