### ISSUE TITLE
Handle quotes/strings in CSV (and similar formats)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/DataVec#27]
Example line that is problematic with current functionality: (note the comma within the entry)
```
1,0,3,"Braund, Mr. Owen Harris",male
```

Currently, there is no way to handle strings in quotes or anything with things like CSVRecordReader. Being able to specify an extra flag for handling strings like this would be good.

**Comment by saudet** [comment]
I'll leave you merge the PRs...
