### ISSUE TITLE
Add pairwise analysis features

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/DataVec#270]
Priority: Low

The idea: sometimes we want to perform analysis between two (or more) columns.
For example:
- Correlation: Spearman and Pearson
- X/Y scatterplots for two columns

My thinking is that we'd implement support for these things, but done on user-specified pairs of columns only... for example, calculating correlations or producing scatterplots for hundreds of features means 10k+ pairs if we did all of them, which isn't really possible to do (or, interpret).

**Comment by huitseeker** [comment]
Probably in the same effort as #117

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/issues/5196
