### ISSUE TITLE
Parent directories containing periods are erroneously filtered

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/DataVec#273]
#### Issue Description

When using a dataset where data files are organized into labelled directories, if the label (parent) directory of the record contains a `.` then `ParentPathLabelGenerator` will mistakenly use the parent directory as the label.

For example, if a dataset is structured as:
```
/msceleb
  - m.1298
    -- 1.jpg
    -- 2.jpg
  - m.088d832
    -- 1.jpg
    -- 2.jpg
```

When ParentPathLabelGenerator is used by a RecordReader such as ImageRecordReader, the label selected is ultimately `msceleb` and not the child directories. This will cause total labels to equal `1`. If no label generator is provided, then total labels will be `0`.

#### Version Information

Current master

#### Contributing

Investigating possible fixes currently.

**Comment by raver119** [comment]
Is this issue still viable?
