### ISSUE TITLE
LibSvm etc tests failing on master

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/DataVec#284]
![image](https://cloud.githubusercontent.com/assets/2360237/26306060/45ba3d38-3f35-11e7-8b61-270329bccb9e.png)

Probably due to this PR, as all tests were passing approx. 48 hours ago:
https://github.com/deeplearning4j/DataVec/pull/282

cc @turambar

**Comment by turambar** [comment]
@AlexDBlack fix here: https://github.com/deeplearning4j/DataVec/pull/286

**Comment by huitseeker** [comment]
Fix merged.
