### ISSUE TITLE
Add common univariate data transforms (Box-Cox etc)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/DataVec#287]
For example: Box-Cox transforms, and related tranforms. 

https://www.researchgate.net/publication/284261483_Improving_your_data_transformations_Applying_Box-Cox_transformations_as_a_best_practice

[Box-Cox Transformations_An Overview.pdf](https://github.com/deeplearning4j/DataVec/files/1020997/Box-Cox.Transformations_An.Overview.pdf)

**Comment by cinqs** [comment]
Waiting for more information... still using matlab...

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/issues/5197
