### ISSUE TITLE
Add Schema and Transform support for NDArrayWritable

### ISSUE THREAD

**Issue by turambar** [deeplearning4j/DataVec#289]
#### Issue Description

We currently lack an efficient column-based String Transform for converting a text field to bag-of-words (BOWs). We do have [StringListToCategoricalSet](https://github.com/deeplearning4j/DataVec/blob/master/datavec-api/src/main/java/org/datavec/api/transform/transform/string/StringListToCategoricalSetTransform.java), but it's not scalable to large vocabularies.

I discussed this with @AlexDBlack, and we decided the principled approach is to add NDArrayWritable as a "type" for columns. This requires support in both Schema and Transform. It will also have implications for analysis and saving to disk. When saving to, e.g., a CSV, we think the right approach is to encode the NDArray object using Base64 and then write the Base64 string into the CSV. That way when the CSV is read from disk, we can properly decode it back into an NDArray.

Once this is added, we can, for example, create a StringToBOWTransform that wraps the BOW Vectorizer, etc.

#### Version Information

All versions

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by turambar** [comment]
As discussed, @AlexDBlack

**Comment by AlexDBlack** [comment]
Some initial thoughts
- Restrict NDArrays to the same size, and specify this size in the schema
- AnalyzeSpark etc - probably just ignore NDArrayWritable columns
- Threading: we'll be passing arrays between threads constantly (with something like spark). Need to make sure we don't run into any issues as a result.

Some alternative approaches:
- java arrays (int[], float[] etc) Writable objects
- a general-purpose array type (could be useful and much more efficient, for example, for bitsets and the like)
- record binarization (i.e., binary storage format) https://github.com/deeplearning4j/DataVec/issues/77

**Comment by AlexDBlack** [comment]
Implemented here: https://github.com/deeplearning4j/DataVec/pull/302
