### ISSUE TITLE
Make TransformProcess normalization not require separately calculated DataAnalysis

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/DataVec#29]
Currently:
TransformProcess.Builder.normalize(String column, Normalize type, DataAnalysis da)
I don't like the fact that we need to separately calculate and then provide the DataAnalysis thing there (which is only used for min/max/mean/stdev values) - this could be calculated internally

**Comment by agibsonccc** [comment]
Of note: I sort of did this here: https://github.com/deeplearning4j/DataVec/pull/95 with the introduction of dataframes and a normalization class. Not a final solution though.

**Comment by raver119** [comment]
Is this issue still viable?

**Comment by agibsonccc** [comment]
This is a nice to have. I'd leave it.

**Comment by AlexDBlack** [comment]
Will be handled as part of pending update/rewrite.
