### ISSUE TITLE
Update documentation of new images pipelines

### ISSUE THREAD

**Issue by huitseeker** [deeplearning4j/DataVec#292]
#### Issue Description

As described here:https://github.com/deeplearning4j/dl4j-examples/issues/420
We need to update
https://deeplearning4j.org/simple-image-load-transform
to reflect the use of `PipelineImageTransform`.

**Comment by huitseeker** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Image support for the Transform process](https://trello.com/c/tyLqHQPH/4-image-support-for-the-transform-process)

**Comment by kepricon** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/3499
