### ISSUE TITLE
Add percentile information to data analysis object?

### ISSUE THREAD

**Issue by eraly** [deeplearning4j/DataVec#293]
#### Issue Description
Running DataAnalysis now takes a number for histogram buckets. 

In the case of highly skewed/unbalanced data (say percentages where most values are between 99.00 and 100.00 and very sparse elsewhere) most of the data ends up in one bucket. 

Perhaps we can add in something that will also give us percentile information. 

As an eg.

Data: 0,10,10,20,50,99,100,100,101,102
percentilePointInterval = 10;

DataAnalysis dataAnalysis = AnalyzeSpark.analyze(schema, parsedInputData, maxHistogramBuckets, percentilePoint);

And the dataAnalysis information contains the information for the 10th 20th .. 100th percentile

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version - 0.8.1-SNAPSHOT

#### Contributing
Not urgent. Functionality in place with boolean conditioning etc.

**Comment by AlexDBlack** [comment]
Added long ago via TDigest: https://github.com/deeplearning4j/DataVec/blob/ec4c2418367a7bf9a50a72ae1efec81896fc5b08/datavec-api/src/main/java/org/datavec/api/transform/analysis/columns/NumericalColumnAnalysis.java#L49
