### ISSUE TITLE
Text writable is inefficient, has considerable overhead

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/DataVec#296]
https://github.com/deeplearning4j/DataVec/blob/master/datavec-api/src/main/java/org/datavec/api/writable/Text.java

~29% of time (in my CSV sequence use case) is spent converting String to byte[] and then back to Strings ;/

![image](https://cloud.githubusercontent.com/assets/2360237/26538174/06d6d42a-4488-11e7-8561-a1d3f507c660.png)

**Comment by turambar** [comment]
I expect this is going to byte me as well.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/issues/5199
