### ISSUE TITLE
Formatter: breaks copyright formatting

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/DataVec#299]
After running "mvn formatter:format" on DataVec, copyrights notices look as follows:
![image](https://cloud.githubusercontent.com/assets/2360237/26576548/993abcd4-456c-11e7-8790-683681f346a3.png)

**Comment by huitseeker** [comment]
Yes, expected behavior. The issue is in the shape of the copyright comment (see § 5.1.1 here:
http://www.oracle.com/technetwork/java/codeconventions-141999.html )
 The fix is here : 
https://github.com/deeplearning4j/DataVec/commit/1d5c7db0ce2bbcb917625246e90fca4433e73f7c
