### ISSUE TITLE
Sequence record readers: derive labels from file path

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/DataVec#30]
Consider CSV sequence data, one sequence per file, where labels are based on the folder structure:

```
\class0\
     file0.csv
     file1.csv
     ...
\class1\
    file0.csv
    file1.csv
    ....
```

A typical use case here is sequence classification.
Currently, we do not have functionality to do this easily.

**Comment by saudet** [comment]
Sounds like ParentPathLabelGenerator could do this right?

**Comment by AlexDBlack** [comment]
Yeah, that would be the way to assign labels to each sequence.
The challenge then for time series is what you do with it: do you duplicate the writable label for each time step? Or add it at the end for sequence classification, using either nothing or NullWritables for padding the other time steps?

**Comment by jpatanooga** [comment]
Vectorizing timeseries is "here be dragons" in a lot of ways. many vector
formats do not account for these things. Feel free to be creative here.

**Comment by raver119** [comment]
Is this issue still viable?

**Comment by AlexDBlack** [comment]
On reflection: if we haven't needed to implement this in 2 years since the original issue, maybe we can just close this :)
