### ISSUE TITLE
RecordReader: Writable caching + reuse

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/DataVec#301]
![image](https://cloud.githubusercontent.com/assets/2360237/26674219/0f6f6a02-4703-11e7-9a8c-1488157b7c4e.png)

^ That's a sequence record reader, batch size 64, ~140 values per time step and long (>>1k steps) sequences.

The idea: don't rely on GC for writables - when we are done with writable objects, return them back to a global pool, and fetch from the global pool instead of creating new ones.

**Comment by raver119** [comment]
Good thing here, is cyclic workload again. Basically it'll be the same step size for each iteration, so it'll be perfectly cache-able.

**Comment by AlexDBlack** [comment]
We can also do this with TransformProcess/Spark use cases too.
And we can even use cache between examples for RecordReaderDataSetIterator, cutting down by a factor of minibatchSize, in theory.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/issues/5200
