### ISSUE TITLE
Failing Test TestSparkStorageUtils

### ISSUE THREAD

**Issue by huitseeker** [deeplearning4j/DataVec#305]
#### Issue Description

After 46400bcc701a111895c6b7a39f386d05b35db973, i.e. after https://github.com/deeplearning4j/DataVec/pull/304:

```
Failed tests: 
  TestSparkStorageUtils.testSaveRestoreMapFile:78 expected:<[zero, 0, 0.0]> but was:<[two, 22, 22.0]>
  TestSparkStorageUtils.testSaveRestoreMapFileSequences:131 expected:<[[zero, 0, 0.0], [one, 1, 1.0], [two, 2, 2.0]]> but was:<[[Bzero, 10, 10.0], [Bone, 11, 11.0], [Btwo, 12, 12.0]]>
```
See
https://github.com/deeplearning4j/DataVec/blob/master/datavec-spark/src/test/java/org/datavec/spark/storage/TestSparkStorageUtils.java#L76-L78

Same issue in https://github.com/deeplearning4j/DataVec/blob/master/datavec-spark/src/test/java/org/datavec/spark/storage/TestSparkStorageUtils.java#L76-L78

**Comment by AlexDBlack** [comment]
Fixed here: #307
Thanks for flagging this.
