### ISSUE TITLE
Replacement of InputSplit for RecordReader usage

### ISSUE THREAD

**Issue by papperwing** [deeplearning4j/DataVec#320]
When user is creating his own RecordReader most of the time he must deal with InputSplit. Most of the Record readers don't even use base InputSplit functions as locations(), locationsIterator() and these method return nonsense data like empty URI array etc. 

Whole InputSplit could be replaced by new interface DataFeeder which could be much simpler and could solve problem of creating empty methods just fore sake of interface.

InputSplit than could inherit from this DataFeeder and so the logic of RecordReaders which count on InputSplit.

Example of DataFeeder interface:
https://gist.github.com/papperwing/2bbe1803da37d54870e3c7018dcb65f9

**Comment by AlexDBlack** [comment]
We will be implementing usability improvements for this part of the ETL pipeline in some upcoming proposed improvements to datavec.
