### ISSUE TITLE
Use of Java 8 APIs

### ISSUE THREAD

**Issue by wmeddie** [deeplearning4j/DataVec#327]
#### Issue Description

DataVec (In particular things implementing IAggregableReduceOp) are using Java 8 APIs.

Are we doing the Java 8 upgrade for 0.8.1?  If not we should remove the Java8-isms before release.

**Comment by AlexDBlack** [comment]
We're using backported function interfaces, and so *should* still be java 7 compliant: https://github.com/deeplearning4j/DataVec/blob/master/datavec-api/pom.xml#L133-L149

**Comment by huitseeker** [comment]
What @AlexDBlack said.
