### ISSUE TITLE
Add a MapFile record writer for local data conversion

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/DataVec#337]
Idea: you have some record reader in either an inefficient format (CSV) or something that can't easily be shuffled (CSV, ARFF, LibSVM).

Solution: we add the ability to easily convert to a hadoop map file, which is:
(a) efficient/binary
(b) support random/shuffled reading

This could be one line, for local operations: perhaps...
MapFileCreator.createMapFile(RecordReader source, File output, int numSplits)

**Comment by turambar** [comment]
I second this.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/DataVec/pull/348

MapFileRecordWriter / MapFileSequenceRecordWriter + https://github.com/deeplearning4j/DataVec/blob/master/datavec-api/src/main/java/org/datavec/api/records/converter/RecordReaderConverter.java
