### ISSUE TITLE
Transforms - allow Categorical state values to be collected automatically

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/DataVec#34]
Currently: state names for categorical column have to be provided manually.
It should be possible to collect these automatically. This is most important where the state names either aren't known, or are very large (where entering them manually becomes tedious or impractical).

Challenge here: current design for schemas assumes that the state names are available initially.

**Comment by AlexDBlack** [comment]
Workaround for now: AnalyzeSpark.getUnique as a first step.
https://github.com/deeplearning4j/DataVec/blob/91ad988a78d562bae92911161506e3c91e69e850/datavec-spark/src/main/java/org/datavec/spark/transform/AnalyzeSpark.java#L566

**Comment by raver119** [comment]
Is this issue still viable?

**Comment by AlexDBlack** [comment]
TransformProcess has a convenience method for this. It's not ideal, but it's good enough until the planned improvements are implemented.
