### ISSUE TITLE
DataVec-Local TableRecords.fromRecordsAndSchema(...) fails for non-float data.

### ISSUE THREAD

**Issue by MikeDepies** [deeplearning4j/DataVec#341]
Table construction from schema works fine, but the data extraction doesn't work with any data aside from floats. Throws casting exception if non-float.
https://github.com/deeplearning4j/DataVec/blob/master/datavec-local/src/main/java/org/datavec/local/transforms/TableRecords.java#L828

Edit: closer inspection that it's expecting to work with NDArrayWritables(which would be floats?)

**Comment by AlexDBlack** [comment]
No longer relevant.
