### ISSUE TITLE
Review BalancedPathFilter

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/DataVec#347]
BalancedPathfilter: the idea is good - provide a more balanced distribution of classes for the training data.

In practice: it often ends up being:
(a) too aggressive, leaving only a very small training set behind, and
(b) unclear to the user exactly what the end result is (how many are left? how many were filtered?)

**Comment by saudet** [comment]
Some ideas here:
https://github.com/deeplearning4j/DataVec/issues/222#issuecomment-297610572

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/issues/5203
