### ISSUE TITLE
RecordConverter, are there docs for this?

### ISSUE THREAD

**Issue by tomthetrainer** [deeplearning4j/DataVec#351]
See this pull request and see if it has documentation or an example. 
  https://github.com/deeplearning4j/DataVec/pull/350

**Comment by AlexDBlack** [comment]
@tomthetrainer no docs or examples on this yet AFAIK. RecordConverter is mainly for internal use though - most users shouldn't need to use it directly.

**Comment by tomthetrainer** [comment]
alright , closing then.
