### ISSUE TITLE
Export datavec schema to Spark SQL schema

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/DataVec#357]
#### Issue Description

Having the ability to export a datavec schema to a [spark-sql](https://spark.apache.org/sql/) schema - and vice-versa - would be very valuable for data exploration and munging cases. For example, when investigating class imbalance you could limit a dataset for specific columns, or only query records that meet a specific criteria.

This would also greatly assist complex ETL cases where CSVs (and other formats) may not be in a desirable state.

#### Version Information

master

#### Contributing

@AlexDBlack thoughts here? I could greatly use this, having some guidance I can get on this.

**Comment by crockpotveggies** [comment]
An alternative here is to instead adapt a SQL parser and utilize our own functionality - which may be more ideal for binary (and other) data formats as per @huitseeker.

Suggestions include:
- https://github.com/JSQLParser/JSqlParser
- https://github.com/brunoribeiro/sql-parser

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/issues/5204
