### ISSUE TITLE
Transforms - add option for "replace missing/invalid with the mean/min/most frequent" of non-invalid values

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/DataVec#36]
Use case: column with some invalid values.
Sometimes: want to replace them with the mean value, minimum, or the most commonly occuring value (for categorical).

**Comment by huitseeker** [comment]
The issue being that it's a 2-pass operation :-S

**Comment by raver119** [comment]
Is this issue still viable?

**Comment by AlexDBlack** [comment]
Will be handled in DataVec improvements.
