### ISSUE TITLE
Add a JDBC record reader

### ISSUE THREAD

**Issue by dalsh** [deeplearning4j/DataVec#362]
Proposal for a new record reader to iterate on a jdbc ResultSet and transform rows into record values.

A few remarks and questions with no special order :
- Commons db offers some abstractions but the standard jdbc api may offer more control (in particular concerning paging). JOOQ has interesting features too, like dialect agnostic request generation DSL
- Minimum required parameters should be a datasource and a query
- Any opinion on connection persistence and (potential) pooling ?
- Should this be a separate maven module ?
- How to map relational column types to instances of Writables ? I've seen some related stuff in the interface layer between local and tablesaw's fork in dataframe ([SqlResultSetReader](https://github.com/deeplearning4j/DataVec/blob/master/datavec-dataframe/src/main/java/org/datavec/dataframe/io/jdbc/SqlResultSetReader.java) in this same module seems to be doing some mapping as well)

**Comment by agibsonccc** [comment]
We use commonsdb..jooq is a bit heavy for this but I wouldn't mind using it if done right.

DBUtils/commons db makes more sense

No opinions on pooling.

Yes it should be a separate module.

Writables are generally relative to type. I would look at what the csv record reader does and immitate that.

**Comment by dalsh** [comment]
Thanks for your answers. Concerning the Writables, I meant that CSVRecordReader is always reading Texts, while the JDBCRecordReader may have to read other types of Writable and some mapping should occur.

Can you assign this to me ? Started working on it here https://github.com/dalsh/DataVec/tree/features/jdbc-record-reader-362

**Comment by agibsonccc** [comment]
yes you would need different Writable types: https://github.com/deeplearning4j/DataVec/blob/master/datavec-api/src/test/java/org/datavec/api/records/reader/impl/transform/TransformProcessRecordReaderTests.java#L29

**Comment by dalsh** [comment]
I opened PR #364 so you can start early reviewing.

I have 2 questions :
- what should metadata objects store in order to re-fetch data ? One idea could be to ask the user to provide a primary key column name and a table name so we can store the related key value and table name in the metadata, but that only covers simple cases (if you iterate over a join or select in select request this won't work)

- what's an inputsplit exactly and how should the concept be applied to JDBC record reading ?

**Comment by agibsonccc** [comment]
input splits for data base could be queries or even batched results

for refetching data should be able to reuse the same query I'd imagine?

**Comment by dalsh** [comment]
For refetching data I was mentionning the RecordMetaData that is passed to loadFromMetaData (specifically [this](https://github.com/deeplearning4j/DataVec/blob/master/datavec-api/src/main/java/org/datavec/api/records/reader/RecordReader.java#L138) and [this](https://github.com/deeplearning4j/DataVec/blob/master/datavec-api/src/main/java/org/datavec/api/records/metadata/RecordMetaData.java#L27))
