### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by benmccann** [deeplearning4j/DataVec#384]
Should I be able to just do `mvn compile` to build the project? I'm getting the error below:

[ERROR] Failed to execute goal on project datavec-api: Could not resolve dependencies for project org.datavec:datavec-api:jar:0.9.1-SNAPSHOT: Failed to collect dependencies at org.nd4j:nd4j-native:jar:0.9.1-SNAPSHOT: Failed to read artifact descriptor for org.nd4j:nd4j-native:jar:0.9.1-SNAPSHOT: Failure to find org.nd4j:nd4j-backend-impls:pom:0.9.1-20170810.173019-28 in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced -> [Help 1]

**Comment by agibsonccc** [comment]
Snapshots as of now is a known issue. This will be fixed with the release.

**Comment by benmccann** [comment]
Any tips on how I can workaround it so that I can contribute in the meantime?

When will the release be? Is there somewhere I can track it?
