### ISSUE TITLE
Sequenced Transforms for SparkTransformServer (specifically CSVSparkTransformServer)

### ISSUE THREAD

**Issue by emsixteeen** [deeplearning4j/DataVec#386]
#### Issue Description

Presently SparkTransformServer (concretely CSVSparkTransformServer) only does non-sequenced transforms, and we need a way for it to allow for both, single and sequenced transforms.

#### Version Information

Please indicate relevant versions, including, if relevant:

0.9.1+

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/DataVec/pull/388

**Comment by emsixteeen** [comment]
Doesn't seem to work.

Here's my input JSON (`single.json`):

```
{
  "values": [
    "test"
  ]
}
```

And here's my cURL:

```
curl -v -X POST -H "Content-Type: application/json" -d@single.json http://localhost:9204/transformincremental
```

With that JSON I get an Exception:

```
java.lang.RuntimeException: Cannot execute examples individually: TransformProcess contains a ConvertToSequence operation
```

Ok, that's expected. I change the cURL to:

```
curl -v -X POST -H "Content-Type: application/json" -H "Sequence: True" -d@single.json http://localhost:9204/transformincremental
```

Then, I get this Exception:

```
org.nd4j.shade.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "values" (class org.datavec.spark.transform.model.BatchCSVRecord), not marked as ignorable (2 known properties: "recordsAsString", "records"]
```

Ok, so I change the JSON to (`batch.json`):

```
{
  "records": [
    {
      "values": [
        "test"
      ]
    }
  ]
}
```

Try the same cURL as the last one, and I get this Exception:

```
java.lang.RuntimeException: Cannot execute examples individually: TransformProcess contains a ConvertToSequence operation
```

**Comment by agibsonccc** [comment]
@emsixteeen @crockpotveggies had it work. I have a feeling there's some delta in your config.
@AlexDBlack also added a test case for this specific use case. Could you confirm that everything is updated and you tested the right config? Something seems off here.

**Comment by emsixteeen** [comment]
Yes, everything is up to date.

**Comment by huitseeker** [comment]
Given the above discussion, reopening

**Comment by agibsonccc** [comment]
Works fine..was just broken test. https://github.com/deeplearning4j/DataVec/pull/402
