### ISSUE TITLE
CSVSparkTransform.transformSequenceArrayIncremental incorrect shape

### ISSUE THREAD

**Issue by emsixteeen** [deeplearning4j/DataVec#397]
#### Issue Description

When providing an "incremental" CSV record, which is understood to be a single row of an otherwise arbitrary length CSV dataset, and using a transform with convertToSequence in it, the resultant array's shape seems incorrect. The returned array's shape is [rows, length, features], instead of [rows, features, length].

For example for the single-record input string "test" (with 30 features), the desired output is [1, 30, 4], but currently the output is [1, 4, 30].

#### Version Information

Please indicate relevant versions, including, if relevant:

`master` for all.

**Comment by crockpotveggies** [comment]
`.output()` method expects a single example. Possible explanation of why you're getting this.

**Comment by crockpotveggies** [comment]
@AlexDBlack we've narrowed this to a difference in the shape output of 1-hot rep from a record reader and a datavec transform. Ideas?

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/DataVec/pull/399#pullrequestreview-57340255
