### ISSUE TITLE
Missing JSON annotations on AppendStringColumnTransform

### ISSUE THREAD

**Issue by turambar** [deeplearning4j/DataVec#407]
#### Issue Description

Serialization and deserialization of TransformProcesses using `AppendStringColumnTransform` fail with a Jackson-related error. This is because the required JSON annotations are missing.

#### Version Information

Current version of DataVec

**Comment by turambar** [comment]
Addressed in this PR: https://github.com/deeplearning4j/DataVec/pull/406

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/DataVec/pull/406
