### ISSUE TITLE
ImageRecordReader - add different "reshape" options

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/DataVec#417]
Currently NativeImageLoader resizes an image if required.
It  would be nice to be able to explicitly set the ImageRecordReader to be able to do any of the following, if the original image aspect ratio doesn't match the output image aspect ratio:

- Rescale (current default)
- Center crop
- Pad (i.e., add black bars)

This can matter for things like object detection - rescaling changes the aspect ratio, which may impact performance in some cases (center crop or pad would often be preferred for object detection)

**Comment by saudet** [comment]
When the images are of the right size, they do not get modified, so we can use an ImageTransform to do this kind of custom transformation earlier in the pipeline. Resizing is pretty much just a fallback. I feel it would make sense to add more choices of ImageTransform instead. What do you think?

**Comment by AlexDBlack** [comment]
That would work too. Note that for object detection, we need to also know the original image size (so we can translate the bounding box coordinates after the crop/flip/whatever operations), which is why I added this recently: https://github.com/deeplearning4j/DataVec/blob/master/datavec-data/datavec-data-image/src/main/java/org/datavec/image/data/Image.java#L27-L29

We'd need to think carefully about how to handle those coordinate translations via the ImageTransform code. (See here: https://github.com/deeplearning4j/DataVec/blob/master/datavec-data/datavec-data-image/src/main/java/org/datavec/image/recordreader/objdetect/ObjectDetectionRecordReader.java#L154)

**Comment by saudet** [comment]
We'd just need a ImageTransform.transformCoordinates() method, but
implementing for all transforms will take a bit of time.
