### ISSUE TITLE
ImageRecordReader for regression

### ISSUE THREAD

**Issue by strikerz76** [deeplearning4j/DataVec#422]
#### Issue Description
The ImageRecordReader can only be used for classification because it converts labels to strings and uses them as independent sets. It can't use a range of output values for a label as is needed for regression.

Lines 113 and 203 of BaseImageRecordReader show how the label is converted to a string and added to a list if not already in the list.

**Comment by AlexDBlack** [comment]
Initial thoughts on how to do this: add an isClassification() or isRegression() method to PathLabelGenerator interface. Then only collect set of labels for classification, otherwise just pass through the labels for regression.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/DataVec/pull/423
