### ISSUE TITLE
Wrong Content-Type Header

### ISSUE THREAD

**Issue by emsixteeen** [deeplearning4j/DataVec#427]
#### Issue Description

[`CSVSparkTransformServer`](https://github.com/deeplearning4j/DataVec/blob/master/datavec-spark-inference-parent/datavec-spark-inference-server/src/main/java/org/datavec/spark/transform/CSVSparkTransformServer.java) no longer returns the `Content-Type` header as `application/json` but rather as `text/plain`. Looks like perhaps the changes in #418 introduced this.

#### Version Information

Please indicate relevant versions, including, if relevant:

`master` as of this submission (ee923b0f5f39f1c8e85f9bc480efdf7416565f6a)

**Comment by AlexDBlack** [comment]
FYI you can explicitly set the content type for return values in Play... see for example:
https://github.com/deeplearning4j/deeplearning4j/blob/cb960c8deaee78dceabd49a5c336ad059d78cf83/deeplearning4j-ui-parent/deeplearning4j-play/src/main/java/org/deeplearning4j/ui/play/staticroutes/Assets.java#L52
