### ISSUE TITLE
RotateImageTransform is not working as expected

### ISSUE THREAD

**Issue by eypros** [deeplearning4j/DataVec#433]
#### In an attempt to understand the basic of dl4j I experimented with optically examining an image dataset after a transformation has been applied. The problem is that in reality the image passing through the transformation loses all their information and become single colored images.
The code below is the code provided in the examples (_ImagePipelineExample.java_ to be precise) with some minor changes and the insertion of a RotateImageTransform.

```
package org.deeplearning4j.examples.dataexamples;

import org.datavec.api.io.filters.BalancedPathFilter;
import org.datavec.api.io.labels.ParentPathLabelGenerator;
import org.datavec.api.split.FileSplit;
import org.datavec.api.split.InputSplit;
import org.datavec.api.util.ClassPathResource;
import org.datavec.image.loader.BaseImageLoader;
import org.datavec.image.recordreader.ImageRecordReader;
import org.datavec.image.transform.*;
import org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator;
import org.nd4j.linalg.dataset.DataSet;
import org.nd4j.linalg.dataset.api.iterator.DataSetIterator;

import java.io.File;
import java.util.Random;

/**
 * Created by susaneraly on 6/9/16.
 */
public class ImagePipelineExampleIssue {

    private static final String [] allowedExtensions = BaseImageLoader.ALLOWED_FORMATS;

    private static final long seed = 12345;

    private static final Random randNumGen = new Random(seed);

    private static final int height = 10;//50;
    private static final int width = 10;//50;
    private static final int channels = 3;

    public static void main(String[] args) throws Exception {

        File parentDir=new ClassPathResource("DataExamples/ImagePipeline/").getFile();
        FileSplit filesInDir = new FileSplit(parentDir, allowedExtensions, randNumGen);

        ParentPathLabelGenerator labelMaker = new ParentPathLabelGenerator();
        BalancedPathFilter pathFilter = new BalancedPathFilter(randNumGen, allowedExtensions, labelMaker);

        InputSplit[] filesInDirSplit = filesInDir.sample(pathFilter, 80, 20);
        InputSplit trainData = filesInDirSplit[0];
        ImageRecordReader recordReader = new ImageRecordReader(height,width,channels,labelMaker);

        ImageTransform transform2 = new MultiImageTransform(randNumGen,new RotateImageTransform(45));
        recordReader.initialize(trainData,transform2);
        int outputNum = recordReader.numLabels();
        int batchSize = 1;//10; // Minibatch size. Here: The number of images to fetch for each call to dataIter.next().
        int labelIndex = 1; // Index of the label Writable (usually an IntWritable), as obtained by recordReader.next()

        DataSetIterator dataIter = new RecordReaderDataSetIterator(recordReader, batchSize, labelIndex, outputNum);
        int i = 1;
        System.out.println(dataIter.getLabels());
        while (dataIter.hasNext()) {
            DataSet ds = dataIter.next();
            System.out.println(ds);
            System.out.println("Image no: " + i++);
        }
    }
}



```

#### Version Information

* Deeplearning4j 0.9.1
* win7
* cpu only

**Comment by saudet** [comment]
Where and how are you using RotateImageTransform in your code?

**Comment by eypros** [comment]
Yeah, sorry about that. I copied the unmodified code.
Anyway I just used RotateImageTransform to the code to optically inspect the result in the specified images.

**Comment by saudet** [comment]
Right ok, so what isn't working?

**Comment by eypros** [comment]
As I stated earlier the rotate transform is not working because it destroys the images. All intensities inside the images are becoming 1 single intensity so the image transform to a single color image (e.g. red).

**Comment by tomthetrainer** [comment]
@eypros 
Here is a gist of a working image transform with rotate in dl4j 9.1

https://gist.github.com/tomthetrainer/cf2373ae1e2d6cca7715934e22f53527

Try that, you may have to replace with your own image. 
I initially had some trouble with the image transforms because I was not setting some parameters, rotating into the background, or the edge or some similar problem. 

Try my code, see if it works, then see if you can adjust yours to get proper results.

**Comment by tomthetrainer** [comment]
@eypros 
Actually looking at my comments in that code, I had the same issue you are having. 

See this comment. 
// Rotate and all the pixels are the same

I seemed to have solved the problem, and no longer remember what the issue was. I assume it was the settings, (random, centerx,centery,angle,scale).borderMode(1)

**Comment by eypros** [comment]
@tomthetrainer I think that it works with your parameters.
I tried using an explicit full parameter call to RotateImageTransform i.e. `RotateImageTransform(java.util.Random random, float centerx,float centery,float angle,float scale)` and it works for the default parameters except for the last one (`float scale`).

Since as stated [here ](https://deeplearning4j.org/datavecdoc/org/datavec/image/transform/RotateImageTransform.html) a call to public `RotateImageTransform(float angle)` essentially calls `this(null, 0, 0, angle, 0)` which of course has `scale=0.0` as parameter. 

My guess is that this should have been `scale=1.0` so no scale change to images to be imposed. So, a minor change in this part of the code would fix the issue.

Thanks

**Comment by tomthetrainer** [comment]
@saudet I will take the docs piece, does the code need changed?

**Comment by saudet** [comment]
No, thanks, it's a bug in the code. The adjusted angle wasn't getting used by the warp. 
This fix will get merged soon:
https://github.com/deeplearning4j/DataVec/pull/432/files#diff-7c14cffc22c3fa46fbbb036b61edfab1L112

**Comment by saudet** [comment]
The fix was merged into master. Thanks for the feedback!
