### ISSUE TITLE
Multiple regressions from 0.8.0 to 0.9.1 reading CSV data from InputStream and when input size is unknown. 

### ISSUE THREAD

**Issue by mbkennel** [deeplearning4j/DataVec#435]
#### Issue Description

I'm encountering a number of problems when trying to upgrade from 0.8.0 to 0.9.1.

I'm trying to do something simple which appears to be cumbersome in DL4J, and now is mostly not working for me.

I want to read in a .csv or .csv.gz set of data, whose length is a priori, unknown, into **one** Dataset. Motivation is that I want to shuffle examples over entire Dataset, and I will then myself batch up into minibatch Datasets for training.

I had written some methods which worked in 0.8.0, which now fail in 0.9.1.  I was reading in .gz or not gzipped data previously using InputStreamInputSplit, but this now fails.

In addition, I was previously passing in Integer.MAX_VALUE as the batchsize to a RecordReaderDataSetIterator so that it would read as much data as possible into one Dataset. In 0.9.1 I get a VM allocation error, whereas in 0.8.0 I did not, and I received the entire file.

Please describe your issue, along with:
- expected behavior

All tests on included Maven project pass.  E.g. run_test_0.8.0.sh

- encountered behavior

All but one test on CSV reading fails on run_test_0.9.1.sh.  Only a FileSplit (thereby not permitting .gz to be read), where the length is known ahead of time works. 

I spent some effort making a clean standalone bug project and driver bash scripts to illustrate the problem, so it should be easy to reproduce i hope. 

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version  0.8.0 and 0.9.1
* platform information (OS, etc)  CentOS 6
* CUDA version, if used none
* NVIDIA driver version, if in use none
[DL4JBug.tar.gz](https://github.com/deeplearning4j/DataVec/files/1350663/DL4JBug.tar.gz)

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by mbkennel** [comment]
`
package com.fico.fa.dl4jbug;

import java.io.BufferedInputStream;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.zip.GZIPInputStream;
import java.util.zip.ZipException;
import org.datavec.api.records.reader.impl.csv.CSVRecordReader;
import org.datavec.api.split.FileSplit;
import org.datavec.api.split.InputStreamInputSplit;
import org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator;
import org.nd4j.linalg.dataset.DataSet;
import org.nd4j.linalg.dataset.api.iterator.DataSetIterator;

/**
 * This test shows a regression from 0.8.0 to 0.9.1.
 *
 * My goal is simple: read one CSV or CSV.GZ, of originally unknown length, into memory as one
 * Dataset.
 *
 * Motivation: I want to be able to shuffle examples over entire datasets before creating
 * minibatches.
 *
 * In 0.8.0, I am able to do this. In 0.9.1 there are various problems.
 *
 * @author matthewkennel
 */
public class DL4JBug {

    static String csvPath = "./dl4j_bug_example.csv";
    static String csvGzPath = "./dl4j_bug_example.csv.gz";
    static int expectedLineCount = 15;

    public static InputStream openStreamFromFile(String filepath) throws FileNotFoundException, IOException {
        try {
            return new GZIPInputStream(new FileInputStream(filepath));
        } catch (ZipException e) {
            return new BufferedInputStream(new FileInputStream(filepath));
        }
    }

    public static int countLines(String filepath) {
        int lines = 0;
        try (InputStream inputStream = openStreamFromFile(filepath);
                Reader decoder = new InputStreamReader(inputStream);
                BufferedReader br = new BufferedReader(decoder)) {
            while (br.readLine() != null) {
                lines++;
            }
        } catch (IOException ex) {
            Logger.getLogger(DL4JBug.class.getName()).log(Level.SEVERE, null, ex);
            return -1;
        }
        return lines;
    }

    static int testCSVToDataset(String filePath, int lines) {
        InputStream is = null;
        try {
            is = openStreamFromFile(filePath);
            assert (is != null);
            CSVRecordReader recordReader = new CSVRecordReader(0, ",");
            recordReader.initialize(new InputStreamInputSplit(is));
            DataSetIterator iterator = new RecordReaderDataSetIterator(recordReader, lines);
            // if this were appended with a 'true' then it would have a continuous target.
            // That would conceivably iterate through multiple batches, but as there is just one batch
            // we take it
            //LOG.info("Reading no-label CSV set from {}...", filePath);
            DataSet dataSet = iterator.next();
            recordReader.close();
            return dataSet.numExamples();
        } catch (Exception ex) {
            Logger.getLogger(DL4JBug.class.getName()).log(Level.SEVERE,
                    "Exception in testCSVToDataset", ex);
        } finally {
            try {
                is.close();
            } catch (IOException ex) {
                Logger.getLogger(DL4JBug.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return -1;
    }

    // Don't use the InputStreamInputSplit, use FileSplit instead, which won't
    // allow reading in .csv.gz. 
    static int testCSVToDatasetFileSplit(String filePath, int lines) {
        try {
            CSVRecordReader recordReader = new CSVRecordReader(0, ",");
            recordReader.initialize(new FileSplit(new File(filePath)));
            DataSetIterator iterator = new RecordReaderDataSetIterator(recordReader, lines);
            // if this were appended with a 'true' then it would have a continuous target.
            // That would conceivably iterate through multiple batches, but as there is just one batch
            // we take it
            //LOG.info("Reading no-label CSV set from {}...", filePath);
            DataSet dataSet = iterator.next();
            recordReader.close();
            return dataSet.numExamples();
        } catch (Exception ex) {
            Logger.getLogger(DL4JBug.class.getName()).log(Level.SEVERE,
                    "Exception in testCSVToDatasetFileSPlit", ex);
        } catch (Error ex) {
            Logger.getLogger(DL4JBug.class.getName()).log(Level.SEVERE,
                    "Error in testCSVToDatasetFileSplit", ex);
        }
        return -1;
    }

    static void expect(int expected, int observed, String testName) {
        if (expected == observed) {
            System.out.printf("PASS: %s\n", testName);
        } else {
            System.out.printf("FAIL: %s. Expected %d, observed %d\n", testName, expected, observed);
        }
    }

    public static final void main(String argc[]) {
        expect(expectedLineCount, countLines(csvPath), "countLines of CSV");

        expect(expectedLineCount, countLines(csvPath), "countLines of CSV.gz");

        expect(expectedLineCount, testCSVToDatasetFileSplit(csvPath, expectedLineCount), "Read CSV with FileSplit with known line count");

        expect(expectedLineCount, testCSVToDatasetFileSplit(csvPath, Integer.MAX_VALUE), "Read CSV with FileSplit with unkonwn line count");

        expect(expectedLineCount, testCSVToDataset(csvPath, expectedLineCount), "Read CSV InputStream with known line count");
        expect(expectedLineCount, testCSVToDataset(csvGzPath, expectedLineCount), "Read CSV.gz InputStream with known line count");
        // now test where size is not known ahead of time. 
        expect(expectedLineCount, testCSVToDataset(csvPath, Integer.MAX_VALUE), "Read CSV InputStream with unknown line count");
        expect(expectedLineCount, testCSVToDataset(csvGzPath, Integer.MAX_VALUE), "Read CSV.gz InputStream with unknown line count");

    }

}

`

**Comment by mbkennel** [comment]
```
package com.fico.fa.dl4jbug;

import java.io.BufferedInputStream;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.zip.GZIPInputStream;
import java.util.zip.ZipException;
import org.datavec.api.records.reader.impl.csv.CSVRecordReader;
import org.datavec.api.split.FileSplit;
import org.datavec.api.split.InputStreamInputSplit;
import org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator;
import org.nd4j.linalg.dataset.DataSet;
import org.nd4j.linalg.dataset.api.iterator.DataSetIterator;

/**
 * This test shows a regression from 0.8.0 to 0.9.1.
 *
 * My goal is simple: read one CSV or CSV.GZ, of originally unknown length, into memory as one
 * Dataset.
 *
 * Motivation: I want to be able to shuffle examples over entire datasets before creating
 * minibatches.
 *
 * In 0.8.0, I am able to do this. In 0.9.1 there are various problems.
 *
 * @author matthewkennel
 */
public class DL4JBug {

    static String csvPath = "./dl4j_bug_example.csv";
    static String csvGzPath = "./dl4j_bug_example.csv.gz";
    static int expectedLineCount = 15;

    public static InputStream openStreamFromFile(String filepath) throws FileNotFoundException, IOException {
        try {
            return new GZIPInputStream(new FileInputStream(filepath));
        } catch (ZipException e) {
            return new BufferedInputStream(new FileInputStream(filepath));
        }
    }

    public static int countLines(String filepath) {
        int lines = 0;
        try (InputStream inputStream = openStreamFromFile(filepath);
                Reader decoder = new InputStreamReader(inputStream);
                BufferedReader br = new BufferedReader(decoder)) {
            while (br.readLine() != null) {
                lines++;
            }
        } catch (IOException ex) {
            Logger.getLogger(DL4JBug.class.getName()).log(Level.SEVERE, null, ex);
            return -1;
        }
        return lines;
    }

    static int testCSVToDataset(String filePath, int lines) {
        InputStream is = null;
        try {
            is = openStreamFromFile(filePath);
            assert (is != null);
            CSVRecordReader recordReader = new CSVRecordReader(0, ",");
            recordReader.initialize(new InputStreamInputSplit(is));
            DataSetIterator iterator = new RecordReaderDataSetIterator(recordReader, lines);
            // if this were appended with a 'true' then it would have a continuous target.
            // That would conceivably iterate through multiple batches, but as there is just one batch
            // we take it
            //LOG.info("Reading no-label CSV set from {}...", filePath);
            DataSet dataSet = iterator.next();
            recordReader.close();
            return dataSet.numExamples();
        } catch (Exception ex) {
            Logger.getLogger(DL4JBug.class.getName()).log(Level.SEVERE,
                    "Exception in testCSVToDataset", ex);
        } finally {
            try {
                is.close();
            } catch (IOException ex) {
                Logger.getLogger(DL4JBug.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return -1;
    }

    // Don't use the InputStreamInputSplit, use FileSplit instead, which won't
    // allow reading in .csv.gz. 
    static int testCSVToDatasetFileSplit(String filePath, int lines) {
        try {
            CSVRecordReader recordReader = new CSVRecordReader(0, ",");
            recordReader.initialize(new FileSplit(new File(filePath)));
            DataSetIterator iterator = new RecordReaderDataSetIterator(recordReader, lines);
            // if this were appended with a 'true' then it would have a continuous target.
            // That would conceivably iterate through multiple batches, but as there is just one batch
            // we take it
            //LOG.info("Reading no-label CSV set from {}...", filePath);
            DataSet dataSet = iterator.next();
            recordReader.close();
            return dataSet.numExamples();
        } catch (Exception ex) {
            Logger.getLogger(DL4JBug.class.getName()).log(Level.SEVERE,
                    "Exception in testCSVToDatasetFileSPlit", ex);
        } catch (Error ex) {
            Logger.getLogger(DL4JBug.class.getName()).log(Level.SEVERE,
                    "Error in testCSVToDatasetFileSplit", ex);
        }
        return -1;
    }

    static void expect(int expected, int observed, String testName) {
        if (expected == observed) {
            System.out.printf("PASS: %s\n", testName);
        } else {
            System.out.printf("FAIL: %s. Expected %d, observed %d\n", testName, expected, observed);
        }
    }

    public static final void main(String argc[]) {
        expect(expectedLineCount, countLines(csvPath), "countLines of CSV");

        expect(expectedLineCount, countLines(csvPath), "countLines of CSV.gz");

        expect(expectedLineCount, testCSVToDatasetFileSplit(csvPath, expectedLineCount), "Read CSV with FileSplit with known line count");

        expect(expectedLineCount, testCSVToDatasetFileSplit(csvPath, Integer.MAX_VALUE), "Read CSV with FileSplit with unkonwn line count");

        expect(expectedLineCount, testCSVToDataset(csvPath, expectedLineCount), "Read CSV InputStream with known line count");
        expect(expectedLineCount, testCSVToDataset(csvGzPath, expectedLineCount), "Read CSV.gz InputStream with known line count");
        // now test where size is not known ahead of time. 
        expect(expectedLineCount, testCSVToDataset(csvPath, Integer.MAX_VALUE), "Read CSV InputStream with unknown line count");
        expect(expectedLineCount, testCSVToDataset(csvGzPath, Integer.MAX_VALUE), "Read CSV.gz InputStream with unknown line count");

    }

}
```

**Comment by saudet** [comment]
CSVRecordReader has been rebased on OpenCSV. I don't believe that supports .csv.gz files.

In any case, it's a bug somewhere in the new code. @crockpotveggies If you have a good idea where to look, let us know! Thanks

**Comment by mbkennel** [comment]
It’s only necessary to be able to process an inputStream---look at my code as I was doing it before with 0.8.0 even though nothing on your side supports .csv.gz explicitly.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/issues/5205
