### ISSUE TITLE
The Normalize.MinMax2 document may have a problem

### ISSUE THREAD

**Issue by zyds** [deeplearning4j/DataVec#445]
#### Issue Description

When I try to do some normalize operation， I found the Normalize.MinMax2 document have a problem.
In the document, it's defined  ' 2 * (x-min)/(max-min) + 1 -> maps values to range [-1,1] '
It should be ' 2 * (x-min)/(max-min) - 1 '，right？ 
This will be somewhat misleading.

#### Version Information

the version is 0.9.1 of datavec-api

**Comment by AlexDBlack** [comment]
Yes, it looks like just a javadoc problem. The actual implementation looks correct.
