### ISSUE TITLE
Transformers: Invalid input: (x1,y1), top left position must have values less than (x2,y2) bottom right position.

### ISSUE THREAD

**Issue by DaGump** [deeplearning4j/DataVec#478]
#### Issue Description

Please describe your issue, along with:
- Using the three Transformers (WarpImageTransform, RotateTransformer and FlipImageTransform) ends up in following Exception:
Invalid input: (x1,y1), top left position must have values less than (x2,y2) bottom right position.

@AlexDBlack mentioned in the early adopters chat:
```
the image transforms also translate the bounding box coordinates
but if you L/R flip an image, the top left coordinates are no longer in the top left...
```

I adopted the RedBloodCell test, so the Error occurs:
Source: https://gist.github.com/DaGump/937a597570703ffb0d79620bbdc5a396
Log: https://gist.github.com/DaGump/96f3804ac0a214a400d99a963ea0c2f9

#### Version Information
- Deeplearning4j 0.9.2-SNAPSHOT build on Dec 15t 2017
- nd4j 0.9.2-SNAPSHOT build on Dec 15 2017
- platform information:
- Distributor ID:	LinuxMint
- Description:	Linux Mint 18.2 Sonya
- Release:	18.2
- Codename:	sonya
- CUDA 9.0

**Comment by saudet** [comment]
Fixed with pull #482. Thanks @eduramiba !
