### ISSUE TITLE
CSV loader loads NaN without warning

### ISSUE THREAD

**Issue by SanderGielisse** [deeplearning4j/DataVec#481]
The CSV loader loads NaN values just fine, for example the following line;
0.0,NaN,0.0,0.0

Unfortunately, this nowhere leads to a crash, but instead DL4J just ends up with a loss function score of NaN. Adding a debug option or warning message might save people lots of time when their DL4J program randomly starts printing NaN values.

#### Version Information
* Deeplearning4j version 0.9.1

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/issues/5211
