### ISSUE TITLE
Transform to automatically generate categories from strings

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/DataVec#489]
#### Issue Description
We don't auto infer categories from strings right now.

it should just be a combination of Count unique values -> Assign index

Please describe your issue, along with:
- expected behavior
- encountered behavior

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
* platform information (OS, etc)
* CUDA version, if used
* NVIDIA driver version, if in use

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by AlexDBlack** [comment]
Closing this as resolved - we have TransformProcess.inferCategories methods.
https://github.com/deeplearning4j/DataVec/blob/3d722211b877369ab5ca2b44712a946095d8f811/datavec-api/src/main/java/org/datavec/api/transform/TransformProcess.java#L490-L573
