### ISSUE TITLE
Transforms: add discretization/bucketing for real-valued columns

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/DataVec#49]
Idea: suppose you have a real-valued column, and you want to make this categorical by binning (either for the input, or to train a classifier instead of a regression model).

**Comment by raver119** [comment]
Is this issue still viable?

**Comment by AlexDBlack** [comment]
Yes, this is something we in TransformProcess (or its replacement). Low priority for now.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/issues/5179
