### ISSUE TITLE
Why datavec is bound so tightly with file/uri?

### ISSUE THREAD

**Issue by RuralHunter** [deeplearning4j/DataVec#512]
I'm trying to implement a SequenceRecordReader which reads data from Database/HBase. I checked some interfaces and found most of them(such as InputSplit, RecordMetaData etc) are bound with URI as the basic attribute, which makes hard or unnatural for me to implement the SequenceRecordReader. Most of my data has nothing to do with file paths(URI). They actually are just table names, row identities. Since the interfaces are the most fundamental entities, I wonder how about those interface utilize just String instead of URI as attributes?

**Comment by saudet** [comment]
JDBCRecordReader actually uses a String for the input query:
https://github.com/deeplearning4j/DataVec/blob/master/datavec-jdbc/src/main/java/org/datavec/api/records/reader/impl/jdbc/JDBCRecordReader.java
We could just extend that. Does this answer your question?

**Comment by RuralHunter** [comment]
Thanks. What I plan to do is similar with JDBCRecordReader and that's where my question is raised up. You can see the JDBCRecordReader totally discards the usage of InputSplit but it still has to implement methods with InputSplit parameters. It's just weird from the design point of view. The usage of RecordMetaDataJdbc is also uncomfortable. RecordMetaDataJdbc.getURI() actually returns the URI of the database connection instead of the record which breaks the definition of the RecordMetaData interface. If InputSplit/RecordMetaData use attributes of common type such as String etc, I think these bad smelling code can be avoided.

**Comment by AlexDBlack** [comment]
I will add, briefly, that we have plans to revisit a lot of DataVec in the future. Better support for the wide variety of data sources is one part of those plans. The codebase as it stands today has evolved iteratively over time, keeping a lot of the original design decisions unchanged - some of those design decisions do need to be reviewed.
Anyway, I'll close this for now.
