### ISSUE TITLE
Automatic Augmentation of Data in BalancedPathFilter

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/DataVec#516]
Moved from DL4J issue: https://github.com/deeplearning4j/deeplearning4j/issues/4737

> Currently the BalancedPathFilter Class removes training examples from classes where there are more examples to match classes where there are less examples to balance the training data.
Proposal is to have an option of also automatically increasing the numbers of training examples for the classes with less training examples to match the number of the classes with more training examples. This way we give us more option on how to treat imbalanced Training datasets

Note I'm in favor of having this functionality, but probably would make a new class instead of trying to modify BalancedPathFilter.

**Comment by saudet** [comment]
I think that's pretty much what is proposed in pull #439. We just need someone to polish it up a bit!
/cc @Ngosti2000

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/issues/4737
