### ISSUE TITLE
FileNotFoundException - ClassPathResource reads files in JAR

### ISSUE THREAD

**Issue by jariojose** [deeplearning4j/DataVec#529]
I run the project from IDE and works better, but when I build and run (jar) in terminal I have the error:

 ERROR [2018-03-23 01:57:00,350] com.eneuron.analise.platform.core.satelites.anticheating.nntextclassifier.impl.NNTextClassifier: null
! java.io.FileNotFoundException: /tmp/datavec_temp17644791784216dir/META-INF/MANIFEST.MF (Arquivo ou diretório não encontrado)
! at java.io.FileOutputStream.open0(Native Method)
! at java.io.FileOutputStream.open(FileOutputStream.java:270)
! at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
! at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
! at org.datavec.api.util.ArchiveUtils.unzipFileTo(ArchiveUtils.java:78)
! at org.datavec.api.util.ClassPathResource.getFile(ClassPathResource.java:134)
! ... 13 common frames omitted
! Causing: java.lang.RuntimeException: java.io.FileNotFoundException: /tmp/datavec_temp17644791784216dir/META-INF/MANIFEST.MF (Arquivo ou diretório não encontrado)
! at org.datavec.api.util.ClassPathResource.getFile(ClassPathResource.java:160)
! at org.datavec.api.util.ClassPathResource.getFile(ClassPathResource.java:100)
(...)

**Comment by AlexDBlack** [comment]
I assume you are using ClassPathResource directly in your project? I'd recommend  trying the ND4J ClassPathResource instead: https://github.com/deeplearning4j/nd4j/blob/master/nd4j-common/src/main/java/org/nd4j/linalg/io/ClassPathResource.java

The DataVec ClassPathResource has some issues, and we'll likely end up removing it soon...
https://github.com/deeplearning4j/DataVec/issues/521

**Comment by jariojose** [comment]
Thank you for your help!!

Sorry for the delay to answer. Now, I have the following error:

 java.io.FileNotFoundException: class path resource [cheats/] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/home/jario/repositorios/eneuron/analise/analise-platform/target/analise-platform-1.0-SNAPSHOT.jar!/cheats/


I see the link that there is:    

 /**
     * Get the File.
     * If the file cannot be accessed directly (for example, it is in a JAR file), we will attempt to extract it from
     * the JAR and copy it to the temporary directory, using {@link #getTempFileFromArchive()}
     *
     * @return The File, or a temporary copy if it can not be accessed directly
     * @throws IOException
     */
    @Override
    public File getFile() throws IOException {
        try{
            return super.getFile();
        } catch (FileNotFoundException e){
            //java.io.FileNotFoundException: class path resource [iris.txt] cannot be resolved to absolute file path because
            // it does not reside in the file system: jar:file:/.../dl4j-test-resources-0.9.2-SNAPSHOT.jar!/iris.txt
            return getTempFileFromArchive();
        }
    }

So, I tried with object.getTempFileFromArchive() but without success (null) because java.lang.ArithmeticException: / by zero (the class doesn't find the folder with files).

**Comment by jariojose** [comment]
I did this:

`iterator = new FileLabelAwareIterator.Builder()
                            .addSourceFolder(new File("cheats/"))
                            .build();`

But, a got a different error:

`INFO  [2018-04-03 22:49:25,779] org.deeplearning4j.models.word2vec.wordstore.VocabConstructor: Sequences checked: [0], Current vocabulary size: [0]; Sequences/sec: [0,00];
ERROR [2018-04-03 22:49:25,783] com.eneuron.analise.platform.core.satelites.anticheating.nntextclassifier.impl.NNTextClassifier: null
! java.lang.ArithmeticException: / by zero
! at org.deeplearning4j.models.sequencevectors.SequenceVectors.buildVocab(SequenceVectors.java:145)
! at org.deeplearning4j.models.sequencevectors.SequenceVectors.fit(SequenceVectors.java:207)
! at org.deeplearning4j.models.paragraphvectors.ParagraphVectors.fit(ParagraphVectors.java:644)
! at com.eneuron.analise.platform.core.satelites.anticheating.nntextclassifier.impl.NNTextClassifier.<init>(NNTextClassifier.java:77)
`

**Comment by AlexDBlack** [comment]
The fact that you are stil running into the FileNotFoundException suggests perhaps you were using an old version of ND4J's ClassPathResource? It was updated with that try/catch block reasonably recently.

More geneally, I would suggest not trying to build a data pipeline where the source files are in the JAR itself. Though it *can* work (indeed, stuff like getTempfileFromArchive() should be enough) it might simply be easier (and less error prone) to have it separate to the JAR.

**Comment by jariojose** [comment]
Thank Alex! Great suggestion. I had thought it!

I will update ND4J, but I will follow your suggestion too. Thank you!!
