### ISSUE TITLE
ClassPathResourceTest fails on Windows if CRLF is conserved

### ISSUE THREAD

**Issue by HDouss** [deeplearning4j/DataVec#553]
ClassPathResourceTest is making assumption on CRLF on Windows when checking file sizes. Using Windows, if one git clone with "as-is" CRLF, the test fails because it assumes different size for Windows.
* Deeplearning4j version : 0.9.1

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/DataVec/pull/554
