### ISSUE TITLE
BaseImageRecordReader initialization with configuration overrides appendLabel

### ISSUE THREAD

**Issue by HDouss** [deeplearning4j/DataVec#555]
#### Issue Description

When initializing an `ImageRecordReader` with a passed configuration, the initialization overrides `appendLabel` to false. So, if the `ImageRecordReader` is instantiated with a label generator, and then, initialized with a configuration, many issues arise because `appendLabel` was set to false

I expect the initialization to keep the existing value of `appendLabel` if not set in the configuration like it is the case for the height and the width.
#### Version Information

* Deeplearning4j version : 0.9.1

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/DataVec/pull/554
