### ISSUE TITLE
Reuse buffers in BaseImageRecordReader

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/DataVec#571]
The byte[] allocations here can add up to a lot of memory and GC thrashing:

https://github.com/deeplearning4j/DataVec/blob/9a104e7cd8d759e5fc7f3eac1bd01f5c5454bff0/datavec-data/datavec-data-image/src/main/java/org/datavec/image/loader/NativeImageLoader.java#L404

![image](https://user-images.githubusercontent.com/2360237/39344754-b2361452-4a27-11e8-8577-b3aabbb73481.png)

**Comment by AlexDBlack** [comment]
Some thoughts here:
A simple solution is keep the largest (so far) required byte[] buffer in NativeImageLoader... it would have to be per thread, or a simple pool (shared between threads). try/catch on loading, allocate a larger one if required.

The only issue with that is that what happens if we're done with image loading in our program? that byte[] can never be cleanup up by the GC. But given it's the raw File bytes (I think?) it should only be a few MB, maybe this doesn't matter.

A slightly more sophisticated option might be a pool/queue of weak references - reuse the byte[] if available, but allow it to be GC. Reliable and easy - but the downside of that is that we end up with more allocations/deallocations than if we just kept a hard reference.

Finally (perhaps a bit ugly) we could add a scheduled task to the queue - clear the reference if it doesn't get used for say 30 second.

**Comment by saudet** [comment]
NativeImageLoader already maintains a state and it's not designed to be used across threads, so we can keep a buffer around in a field without any issue. It'll get garbage collected when that instance of NativeImageLoader also gets garbage collected.

**Comment by AlexDBlack** [comment]
@saudet Ah, good point. The byte[] doesn't need to be static. OK, that makes it way easier. :)
