### ISSUE TITLE
The memory occupied by Loader cannot be released

### ISSUE THREAD

**Issue by blackredscarf** [deeplearning4j/DataVec#574]
I use datavec in tomcat.
I find that after each use of `NativeImageLoader.asMatrix(mat)`, the memory will grow by nearly 100MB and will not be released afterwards.

DL4j: 0.9.1
Tomcat: 7.0.82
Javacv: 1.4

**Comment by blackredscarf** [comment]
Oh, maybe MemoryWorkspace can work out

**Comment by saudet** [comment]
It does get released, just not very efficiently. This will probably get sorted out with pull #573.
