### ISSUE TITLE
AnalyzeSpark.getUnique for more than a single feature column

### ISSUE THREAD

**Issue by gffde3** [deeplearning4j/DataVec#71]
Currently getUnique only handles a single column per call.

For larger quantities of data with multiple columns where unique values would be nice to know it'd be handy to be able to specify multiple columns in the method call.

The static method could be something like .getUniques(List<String> columnNames, Schema schema,
JavaRDD<java.util.List<Writable>> data)

with a return type HashMap<String, List<Writable>> where the String is the column name.

**Comment by raver119** [comment]
Is this issue still viable?
