### ISSUE TITLE
Add support for LabelPathGenerator for CSV and other record readers

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/DataVec#72]
Idea: in some cases, the file format may be such that the filename or path itself contains useful information.

For example, if data is split (one file per day) we might want to pull in the date as a column for later preprocessing.
Or, perhaps we have multiple CSV files, where different labels are in different files: \class0\myCsv.txt, \class0\myCsv1.txt, \class1\myCsv2.txt etc

**Comment by raver119** [comment]
Is this issue still viable?

**Comment by AlexDBlack** [comment]
Already planned to be handled in update/rewrite.
