### ISSUE TITLE
Pipeline simplification

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/DataVec#76]
Right now there are a lot of abstractions in machine learning we're still not capturing with these ETL pipelines.

The elephant in the room here is pre and post processing with normalization.

We end up having to maintain a lot of metadata like paths of schemas and transform processes.

It's hard to keep track of where you are in an pipeline when you  have so much state to manage there.
Ideally we define something like a "datavec root directory" that we can play with as we like.

This  datavec directory could have a hierarchy like:
preprocess/
postprocess/

In each of these we could store things like schema information and other metadata related to the pipeline.

Goal: make pipeline persistence configurable and as automated as possible.

**Comment by AlexDBlack** [comment]
Already planned to be handled in update/rewrite.
