### ISSUE TITLE
Make datavec more friendly for inference pipelines

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/DataVec#78]
Right now training is the only first class consideration. Ideally we want as much code re use across train and test as possible.

Data pipelines for training and testing should use the same pre processing such as normalization in production. 

We should be able to persist what a user did during training and allow them to access these things based on loading a model from disk and running it in production.

This is likely going to vary problem to problem, but there are likely some abstractions we can come up with to make this easier.

**Comment by raver119** [comment]
Is this issue still viable?

**Comment by AlexDBlack** [comment]
Definitely important, is planned as part of rewrite.
