### ISSUE TITLE
Datavec debugging

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/DataVec#82]
Datavec needs better debugging facilities for understanding why a pipeline fails.

Right now when running on a spark cluster, it's hard to envision the steps a transform goes through and why particular kinds of edge cases in data pipelines occur.

Datavec should help us interpret failures in data pipelines by adding logging for edge cases. This is similar to what streamsets does. It wraps exceptions as errors and outputs the stack traces to a GUI.

Something that could also help us is error propagation and handling.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/issues/5180
