### ISSUE TITLE
AnalyzeSpark is slow

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/DataVec#84]
https://github.com/deeplearning4j/DataVec/blob/a031eadde151e9eac70543a53fe103ac094f940a/datavec-spark/src/main/java/org/datavec/spark/transform/AnalyzeSpark.java#L555-L555

This is a big bottleneck when running datavec. Some parallelization was talked about in the dev channel. @AlexDBlack 

Currently does 1 aggregate call per column to collect statistics.

**Comment by huitseeker** [comment]
`sampleFromColumnSequence` is essentially doing, if you unpack the call to `sampleFromColumn` (and if you write it in pseudo-code):

    sequenceData.flatten.filter($"columnName").takeSample(false, count)

What you want to do is :

    sequenceData.flatMap((l) => l.filter($"columnName")).takeSample(false, count)

It's literally in Java 8 AFAICT (untested, I'm on a train):

    int colIdx = schema.getIndexOfColumn(columnName);
    sequenceData.flatMap(new FlatMapFunction<List<List<Writable>>, List<Writable>>() {
      public Iterable<List<Writable>> call(List<List<Writable>> l) {
        return l.stream() 
                .map(List::get(colIdx))
                .collect(toList());
      }
    })

**Comment by agibsonccc** [comment]
Pointig this out in particular:
https://github.com/deeplearning4j/DataVec/blob/a031eadde151e9eac70543a53fe103ac094f940a/datavec-spark/src/main/java/org/datavec/spark/transform/AnalyzeSpark.java#L663-L663

**Comment by huitseeker** [comment]
Other ideas :
- Why not [`RDD.sample`](https://spark.apache.org/docs/1.6.2/api/java/org/apache/spark/rdd/RDD.html#sample(boolean,%20double,%20long)) ?
- I see a lot of `cache()`, why is there not an equivalent number of `unpersist()` ? ([ref](https://spark.apache.org/docs/latest/programming-guide.html#rdd-persistence))
- it's scary to write this on `List`s, make triple sure this is called on `ArrayList`s implementations
- if you have k aggregation functions to apply on k specific columns it's in general useful to combine their application in a single aggregattion, where the add returns a tuple of size k, as does the merge. They are simply the canonical tuplification of each individual add and merge function.

**Comment by huitseeker** [comment]
I've been trying to flesh out another idea here : https://github.com/huitseeker/DataVec/compare/master...huitseeker:AnalyzeSpark?expand=1
@AlexDBlack: it should at least avoid you the distinct.count you're doing on every String column.
