### ISSUE TITLE
Add local version of datavec

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/DataVec#87]
Use: https://github.com/lwhite1/tablesaw for column oriented operations.

**Comment by agibsonccc** [comment]
Added dataframe libary in this PR: https://github.com/deeplearning4j/DataVec/pull/95 Still need to add an executor.

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/DataVec/pull/107

**Comment by huitseeker** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Datavec - add local executor](https://trello.com/c/QFy9g3E1/6-datavec-add-local-executor)

**Comment by raver119** [comment]
I guess it's safe to close this issue now?

**Comment by agibsonccc** [comment]
Yep! The arrow PR did it.
