### ISSUE TITLE
Implement statistics persistence for things like normalization pipelines

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/DataVec#89]
Typically in machine learning for things like train/test a  pipeline has state when doing normalization.
We should be able to persist these processes and specify a way to persist these at pipeline run time as well as for loading in to an existing pipeline. The main use case here is using training statistics for inference.

2 suggestions were either a separate path or saving the statistics as part of a json declaration.
While not ideal, it doesn't seem like json declaration would be that bad in practice.

**Comment by AlexDBlack** [comment]
Planned as part of rewrite.
